### ISSUE TITLE
Resolve the CI workaround

### ISSUE THREAD

**Issue by Beanow** [sfosc/sourcecred#1]
Since we now have access to set up CI, I would like to remove the quirk where my fork is hooked up to the builds.

**Comment by Beanow** [comment]
@nothingismagick @adamhjk
Do you mind if I hook up the CI to this repo instead of mine?

I'm running from a self-hosted instance at https://drone.sfosc.robin-it.com/Beanow/sfosc-sourcecred-cron/ as cronjobs on the cloud service are disabled. See https://discourse.drone.io/t/cron-on-cloud-drone-io/3899/4
> Hi there, cron is disabled on cloud.drone.io because Bitcoin miners like to try and abuse the service. For cron you would need to run your own installation. Sorry!

I can point this self-hosted instance to run the cron from this repo instead.
Alternatively I can refactor to CircleCI as they have cronjobs in their free-for-foss service. However going with Circle I believe needlessly backs a closed-source service.

**Comment by nothingismagick** [comment]
That sounds like a nice solution. I am for it.
